//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attocaert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public tbl_user()
        {
            this.tbl_invoice = new HashSet<tbl_invoice>();
        }
    
        public int U_id { get; set; }
        public string u_name { get; set; }
        public string u_contact { get; set; }
        public string u_password { get; set; }
    
        public virtual ICollection<tbl_invoice> tbl_invoice { get; set; }
    }
}
